plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.rabbah.mdb'
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 30
        targetSdkVersion 30
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    api project(':mqtt-lib')
    implementation(name: 'CM30-HardwareLibrary-1.0.9', ext: 'aar')
}
